# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yqcznb.github.io
date_format: "ordinal"
title: 我就是我的博客
subtitle: "人生没有白走的路，每一步都算数！"
description: "阿琛的个人博客"
keywords: 不一样,yinqichen, jade琛
timezone: Asia/Qingdao
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 尹琦琛
organization: 
organization_url: 
github_username: yqcznb
location: qingdao, China
email: 485737827@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yqcznb/yqcznb.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# 
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yqcznb
    repo: blog-comments
    oauth:
        client_id: 85c571ad2d4264183a8f
        client_secret: 50e89f4680fa3777acffcece57187fb4c12df822
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yqcznb
    repo: blog-comments
    clientID: 85c571ad2d4264183a8f
    clientSecret: 50e89f4680fa3777acffcece57187fb4c12df822
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
